# Working with Arrays and Matrixes

In [8]:
import numpy as np

In [12]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

type(arr)

In [17]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing with Array

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[0]

1

In [21]:
arr[1]

2

In [22]:
arr[0] + arr[5]

7

# Indexing with Matrixes

In [23]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matriz[0]

array([1, 2, 3])

In [25]:
matriz[2]

array([7, 8, 9])

In [27]:
matriz[0,2]

3

# Slicing with Arrays

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[0:3]

array([1, 2, 3])

In [31]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [32]:
arr[:2]

array([1, 2])

In [33]:
arr[::3]

array([1, 4, 7])

In [34]:
arr[-1]

9

In [35]:
arr[-3:]

array([7, 8, 9])

# Now Slicing with a Matrix

In [36]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [43]:
matriz3D = [[[1, 2],[3, 4]],[[5, 6],[7, 8]]]

In [44]:
matriz3D

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [45]:
matriz3 = np.array(matriz3D)

In [46]:
matriz3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [47]:
matriz3[0,0,0]

1

In [48]:
matriz3[0,0,1]

2

In [49]:
matriz3[0,1,0]

3

In [50]:
matriz3[0,1,1]

4