In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

## Esto devuelve un array con valore Booleanos

In [4]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
arr[0]

1

## Solo hace print a los valores que este como True

In [6]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [7]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

## Se pueden juntar multiples condicionales

In [8]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

## También se pueden cambiar solo los valores que cumlen con la condición

In [11]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [12]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)