In [4]:
import numpy as np

## Creando lista normal con solo Python

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Creando un Array directamente con NumPy

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creando un Array con pasos especificados

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Creando un Array con valores en 0 y longitud especificada

In [9]:
np.zeros(3)

array([0., 0., 0.])

##  Creando una matriz de 10x10 con valores de 0

In [10]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Le podemos especificar las dimensiones de la matriz

In [11]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Tambien pueden ser valores de 1

In [12]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Creando una distribución de 1 a 10


In [32]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## Creando una distribución de 1 a 100

In [15]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## Creando una matriz con diagonal de valores en 1

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Creando un valor random

In [18]:
np.random.rand()

0.6193631016452421

## Creando un Array con 4 valores random

In [19]:
np.random.rand(4)

array([0.21341548, 0.50108279, 0.82558025, 0.96264464])

## Creando una matriz de 4x4 de valores random

In [21]:
np.random.rand(4,4)

array([[0.34454706, 0.79970365, 0.61352314, 0.19265392],
       [0.88105831, 0.2239304 , 0.68638403, 0.28594543],
       [0.74588514, 0.33084854, 0.33853795, 0.79941551],
       [0.64057921, 0.81139184, 0.40529476, 0.03838052]])

## Creando un valor entero que sea random

In [30]:
np.random.randint(1,15)

8

## Creando una matriz de 10x10 con valores enteros random del 1 al 100

In [31]:
np.random.randint(1,100, (10,10))

array([[45, 63, 40, 20, 95, 24, 76, 33, 32, 56],
       [75, 14, 22, 85, 75, 87, 96, 78, 32, 40],
       [15, 23, 89, 93, 30, 56, 92, 81, 82, 27],
       [90, 38, 55, 62, 16, 53, 93, 49, 38, 22],
       [ 9, 55, 93, 16, 23, 73, 72, 47, 38, 10],
       [99, 66, 15, 86, 15, 14, 46,  7, 28, 52],
       [33, 70, 66, 76, 82, 42, 94, 86, 35, 63],
       [77, 79, 78, 40, 18, 98, 43, 21, 28, 48],
       [92, 93, 44, 38, 72, 99, 92, 92, 44, 66],
       [72,  4, 20, 11,  8, 33, 15, 89,  6,  7]])