# Data Types that exist on NumPy

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

## Default type for arrays on Numpy

In [7]:
arr.dtype

dtype('int64')

## Changing data type to be specifically 'float64'

In [10]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [11]:
arr

array([1., 2., 3., 4.])

In [25]:
arr2 = np.array([9,8,7,6])

In [26]:
arr2

array([9, 8, 7, 6])

In [27]:
arr2 = arr2.astype(np.float64)

In [28]:
arr2

array([9., 8., 7., 6.])

### Changing to boolean value

In [29]:
arr3 = np.array([0,1,0,4,7])
arr3

array([0, 1, 0, 4, 7])

In [30]:
arr3 = arr3.astype(np.bool_)
arr3

array([False,  True, False,  True,  True])

### Changing to string values

In [31]:
arr4 = np.array([0,1,0,4,7])
arr4

array([0, 1, 0, 4, 7])

In [33]:
arr4 = arr4.astype(np.string_)
arr4

array([b'0', b'1', b'0', b'4', b'7'], dtype='|S21')

### Changing to int8 values

In [35]:
arr4 = arr4.astype(np.int8)
arr4

array([0, 1, 0, 4, 7], dtype=int8)