# Ejemplos de Dimensions en NumPy

In [1]:
import numpy as np

# valores escalares (0D)

In [2]:
scalar = np.array(77)
print(scalar)
scalar.ndim

77


0

# valores de array (1D)

In [3]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

# valores de matriz (2D)

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

# valores de Tensor (3D) series de tiempo

In [6]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[40,23,12]],[[1,2,3],[4,5,6],[7,8,9],[40,23,12]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 23 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 23 12]]]


3

# Agregar o Eliminar Dimensiones

## Expandiendo Dimensiones

In [8]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [10]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

## Eliminando Dimensiones

In [15]:
print(vector, '| Dimensiones:' ,vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, '| Dimensiones:' ,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] | Dimensiones: 10
[1 2 3] | Dimensiones: 1
