# Funciones Principales de NumPy

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([17,  3, 12, 18, 11, 19, 12, 17, 11, 12])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[17,  3, 12, 18, 11],
       [19, 12, 17, 11, 12]])

## Funciones para encontrar el Máximo y Mínimo de un array o matriz

In [5]:
arr.max()

19

In [6]:
matriz.max()

19

In [7]:
matriz.max(1)

array([18, 19])

In [8]:
matriz.max(0)

array([19, 12, 17, 18, 12])

In [9]:
arr.argmax()

5

In [10]:
matriz.argmax(1)

array([3, 0])

In [11]:
matriz.argmax(0)

array([1, 1, 1, 0, 1])

In [12]:
arr.min()

3

In [13]:
matriz.min(0)

array([17,  3, 12, 11, 11])

In [14]:
arr.argmin()

1

In [15]:
matriz.argmin(0)

array([0, 0, 0, 1, 0])

In [16]:
matriz.argmin(1)

array([1, 3])

## Función Peak to Peak para saber la distancia más grande que hay en la distribución

In [17]:
arr.ptp()

16

In [18]:
matriz.ptp(0)

array([2, 9, 5, 7, 1])

## Función para encontrar el Percentil deseado

In [19]:
np.percentile(arr,50)

12.0

In [20]:
np.percentile(arr, 0)

3.0

In [21]:
np.percentile(arr, 100)

19.0

## Función para ordenar un array

In [22]:
arr.sort()
arr

array([ 3, 11, 11, 12, 12, 12, 17, 17, 18, 19])

## Para encontrar la mediana de una distribución

In [23]:
np.median(arr)

12.0

In [24]:
np.median(matriz, 0)

array([ 7.5, 14. , 14. , 15. , 15.5])

## Para encontrar la variación estándar

In [25]:
np.std(arr)

4.512205669071392

## Para encontrar la varianza (varación estándar al cuadrado)

In [26]:
np.var(arr)

20.360000000000007

## Para encontrar la mediana (el promedio de los valores)

In [27]:
np.mean(arr)

13.2

## Como hacer una concatenación de 2 array (con error incluido)

In [30]:
a = np.array([[1,2], [3,4]])
b = np.array([5,6])

In [31]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [32]:
a.ndim

2

In [33]:
b.ndim

1

In [39]:
b = np.expand_dims(b, axis=0)

In [40]:
b.ndim

2

In [41]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Como hacer una concatenación en el eje 1 usando la Transpuesta T

In [42]:
np.concatenate((a,b), axis=1
              )

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [44]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
b.T

array([[5],
       [6]])