In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))

In [5]:
arr.shape

(3, 2)

In [6]:
arr

array([[7, 4],
       [8, 5],
       [7, 3]])

In [7]:
arr.reshape(1,6)

array([[7, 4, 8, 5, 7, 3]])

In [10]:
arr.reshape(2,3)

array([[7, 4, 8],
       [5, 7, 3]])

In [11]:
np.reshape(arr, (1,6))

array([[7, 4, 8, 5, 7, 3]])

In [12]:
arr

array([[7, 4],
       [8, 5],
       [7, 3]])

In [13]:
np.reshape(arr,(2,3), 'C')

array([[7, 4, 8],
       [5, 7, 3]])

In [14]:
np.reshape(arr, (2,3), 'F')

array([[7, 7, 5],
       [8, 4, 3]])

In [15]:
np.reshape(arr, (2,3), 'A')

array([[7, 4, 8],
       [5, 7, 3]])