# Cuando vamos a modificar un array es importante hacer una copia para no cambiar el array original

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Este cambio tambien afectara al array original porque hacer referencia al mismo espacio de memoria

In [4]:
trozo_de_array = arr[0:6]
trozo_de_array

array([0, 1, 2, 3, 4, 5])

In [5]:
trozo_de_array[:] = 0
trozo_de_array

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Para evitar esto hay que usar la función .copy() para tener 2 objetos distintos que no se afectan en memoria


In [8]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])